### PR TITLE
Fixes setup.py

### LINKED ISSUE #3: Make setup.py work
There was a large overhaul of the engine so setup.py almost definitely doesn't work. It needs to create an extension out of all the .cpp files in `pydanmaku` named `pydanmaku.so` and install it to the `site-packages` folder (as most setup.py do). Any .py files are irrelevant to the package and are either legacy code or for testing.

### PR DESCRIPTION
**Pull request by skyripley**
Fixes #3 
Just needed to create `pydanmaku/__init__.py` and add a version so I added what was in `pydanmaku_old/__init__.py`, which was `__version__ = '0.0.1-alpha1'`. `python setup.py install` and `python setup.py build` were successful. Let me know if anything should be added for this PR.

### CODE REVIEW

**Comment by hanss314** [comment]
This builds, but produces an empty package 
```py
import pydanmaku
>>> dir(pydanmaku)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__']
```
Also, it does not need an `__init__.py` as it is supposed to be building a .so file and installing that to `site-packages`

**Comment by skyripley** [comment]
Is there any reason to not just declare the version in `setup.py` rather than reading it from another file then? The only reason `setup.py` wasn't working was because it was trying to read an `__init__.py` file that didn't exist.

**Comment by hanss314** [comment]
I don't think you understand what I'm asking. I need a new setup.py that compiles and installs a .so extension from the .cpp files. Docs [here](https://docs.python.org/3/distutils/setupscript.html#extension-source-files)

**Comment by skyripley** [comment]
Ah my fault - didn't understand. Closing the pull request as it clearly doesn't address the issue. Thanks for the clarification.

**Pull request closed without merging**
